[package]
name = "httploadtesting"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
threadpool = "1.8.1"
clap = { version = "4.5.15", features = ["derive"] }